name: Executed every Friday

on:
  schedule:
  - cron: "0 9 * * 5"
  # Trigger manually the script
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Cache NPM dependencies
        id: npm_cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        env:
            CI: 1
        run: npm ci

      - name: Execute the Friday cron script
        run: node ./scripts/fridayCron.js
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}